spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:mysql://mysql-uavu.railway.internal:3306/railway?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: jqqlgVmhXZiFWPMspGOYFaqAxGfyQALO
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  base-url: https://deallockecommercefullstackspringboot-production.up.railway.app
  admin-phones: ""

emailjs:
  service-id: service_1zcjm5s
  template-id: template_q5fd69o
  public-key: BAh34rQaol2wbi-fC
  private-key: yIYRSv0JkxnjeBGgSO9nP

twilio:
  account-sid: ""
  auth-token: ""
  phone-number: ""

server:
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict
